# Activity Instructions

Form a group of 2 people. Complete both problems. Take turns and help each other the different tasks!

This should take you no more than **15 minutes** (likely less than that!)

Remember you can ask for advice/help!

## Tasks

###1. Create a 3D array where the values represent the number of days in the month and each row represents the following months of year 1000 AD.

* 1st row: Jan-Apr
* 2nd row: May-Aug
* 3rd row: Sept-Dec

In [5]:
#TODO
import numpy as np
array = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

month_array = array.reshape(3, 4, 1)
print(month_array)

[[[31]
  [28]
  [31]
  [30]]

 [[31]
  [30]
  [31]
  [31]]

 [[30]
  [31]
  [30]
  [31]]]


###2. Use Leibniz’s formula to calculate $\pi$. The formula is
$\pi = 4 \cdot \left(1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \dots\right)$

Though some math is needed to establish this, we can use arrays to convince ourselves that the formula works. Let’s calculate the first 5000 terms of Leibniz’s infinite sum and see if it is close to $\pi$.

$\pi = 4 \cdot \left(1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \dots - \frac{1}{9999} \right)$

Hint: Use arange.


In [14]:
#Todo
rng = np.arange(1, 10000, 2)

min_range = (-1) ** np.arange(5000)

leibniz = min_range / rng

pi = 4 * np.sum(leibniz)
pi

3.1413926535917924

# Resources

* https://jakevdp.github.io/PythonDataScienceHandbook
    + Introduction to NumPy
* Google 😄